### ISSUE TITLE
I should be able to navigate between the details page and the top 100 page

### ISSUE THREAD

**Issue by Adelle-Pitsas** [dgubko/board-game-bonanza#15]
Acceptance Criteria:

- [x] Create an on-click for the board game in `Top100` so that the url is changed and we can see that board game's details (Kiko and Courtney)
- [x] Create a link wrapped button to bring the user back home when it is clicked (Dmitrii, Ryan, Adelle)

**Comment by dgubko** [comment]
The functionality has been created
